FROM nvcr.io/nvidia/tensorflow:19.02-py3

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && pip install --upgrade keras tqdm pillow matplotlib cython

RUN apt install -y git sshfs

RUN pip install git+https://github.com/waleedka/coco.git#subdirectory=PythonAPI

WORKDIR /work